[Icon Theme]
Name=tokodon-dark
Name[ca]=tokodon-dark
Name[ca@valencia]=tokodon-dark
Name[cs]=tokodon-tmavý
Name[es]=tokodon-oscuro
Name[fr]=Tokodon sombre
Name[it]=tokodon-scuro
Name[ka]=tokodon-dark
Name[nl]=tokodon-dark
Name[pt]=tokodon-escuro
Name[sl]=tokodon-temen
Name[tr]=tokodon-koyu
Name[uk]=tokodon-dark
Name[x-test]=xxtokodon-darkxx
Inherits=tokodon
Directories=scalable

[scalable]
Size=22
Type=Scalable
