# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

include:
  - project: sysadmin/ci-utilities
    file:
      - /gitlab-templates/reuse-lint.yml
      - /gitlab-templates/linux.yml
      - /gitlab-templates/linux-qt6.yml
      - /gitlab-templates/freebsd.yml
      - /gitlab-templates/freebsd-qt6.yml
      # - /gitlab-templates/android.yml
      # - /gitlab-templates/android-qt6.yml

      - /gitlab-templates/flatpak.yml
      - /gitlab-templates/craft-android-apks.yml

      # Blocked on libass (a MPV dependency) not compatible with MSVC at the moment
      # - /gitlab-templates/windows.yml
      # - /gitlab-templates/windows-qt6.yml
      # - /gitlab-templates/craft-windows-x86-64.yml
