# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

include:
  - project: sysadmin/ci-utilities
    file:
      - /gitlab-templates/reuse-lint.yml
      - /gitlab-templates/linux-qt6.yml
      - /gitlab-templates/freebsd-qt6.yml
      - /gitlab-templates/android-qt6.yml

      # Blocked on libass (a MPV dependency) not compatible with MSVC at the moment
      # - /gitlab-templates/windows.yml
      # - /gitlab-templates/windows-qt6.yml

      # Blocked on KF6 runtime not available
      # - /gitlab-templates/flatpak.yml

      # Blocked on https://invent.kde.org/packaging/craft-blueprints-kde/-/merge_requests/699
      #- /gitlab-templates/craft-android-qt6-apks.yml
