# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
  - 'on': [ 'Linux', 'FreeBSD', 'Windows', 'Android' ]
    'require':
      'frameworks/extra-cmake-modules': 'Frameworks/6.24'
      'frameworks/ki18n': 'Frameworks/6.24'
      'frameworks/kirigami': 'Frameworks/6.24'
      'frameworks/kcoreaddons': 'Frameworks/6.24'
      'frameworks/knotifications': 'Frameworks/6.24'
      'frameworks/kconfig': 'Frameworks/6.24'
      'frameworks/kcolorscheme': 'Frameworks/6.24'
      'frameworks/kiconthemes': 'Frameworks/6.24'
      'frameworks/kitemmodels': 'Frameworks/6.24'
      'frameworks/kdeclarative': 'Frameworks/6.24'
      'frameworks/prison': 'Frameworks/6.24'
      'libraries/kirigami-addons': 'v1.11.0'
      'third-party/qtkeychain': '@latest'
      'third-party/qcoro': '@latest'

  - 'on': [ 'Linux', 'FreeBSD', 'Windows' ]
    'require':
      'frameworks/kcrash': 'Frameworks/6.24'
      'frameworks/qqc2-desktop-style': 'Frameworks/6.24'

  - 'on': [ 'Linux', 'FreeBSD', 'Android' ]
    'require':
      'libraries/kunifiedpush': '@latest-kf6'

  - 'on': [ 'Linux', 'FreeBSD' ]
    'require':
      'frameworks/kdbusaddons': 'Frameworks/6.24'
      'frameworks/kwindowsystem': 'Frameworks/6.24'
      'frameworks/kio': 'Frameworks/6.24'
      'frameworks/purpose': 'Frameworks/6.24'

  - 'on': ['Linux']
    'require':
      'sdk/selenium-webdriver-at-spi': '@latest'

Options:
  require-passing-tests-on: [ '@all' ]
