version = 1
SPDX-PackageName = "Tokodon"
SPDX-PackageSupplier = "Carl Schwan <carl@carlschwan.eu>"
SPDX-PackageDownloadLocation = "https://invent.kde.org/network/tokodon"

[[annotations]]
path = ["README.md", "src/autotests/data/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Carl Schwan <carl@carlschwan.eu>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["CONTRIBUTING.md", "src/purpose/purposeplugin.json"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Joshua Goins <josh@redstrate.com>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["org.kde.tokodon.svg", "logo.png", "android/res/drawable/tokodon.png"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Bugsbane <https://invent.kde.org/bugsbane>"
SPDX-License-Identifier = "CC-BY-SA-4.0"

[[annotations]]
path = ["src/content/elephant.svg", "src/content/mastodon-logo.svg"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Mastodon contributors"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = ".flatpak-manifest.json"
precedence = "aggregate"
SPDX-FileCopyrightText = "Nicolas Fella <<nicolas.fella@gmx.de>>"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = ["android/ic_launcher-playstore.png", "android/res/drawable/ic_launcher_background.xml", "android/res/drawable/ic_launcher_foreground.xml", "android/res/mipmap-anydpi-v26/ic_launcher.xml", "android/res/mipmap-anydpi-v26/ic_launcher_round.xml", "android/res/mipmap-hdpi/ic_launcher.png", "android/res/mipmap-mdpi/ic_launcher.png", "android/res/mipmap-xhdpi/ic_launcher.png", "android/res/mipmap-xxhdpi/ic_launcher.png", "android/res/mipmap-xxxhdpi/ic_launcher.png", "fastlane/metadata/org.kde.tokodon/en-US/images/featureGraphic.png"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Alois Spitzbart <spitz234@hotmail.com>"
SPDX-License-Identifier = "CC-BY-SA-4.0"
