[Icon Theme]
Name=tokodon
Name[ca]=tokodon
Name[ca@valencia]=tokodon
Name[cs]=tokodon
Name[de]=Tokodon
Name[en_GB]=tokodon
Name[es]=tokodon
Name[eu]=tokodon
Name[fi]=tokodon
Name[fr]= Tokodon
Name[gl]=tokodon
Name[it]=tokodon
Name[ka]=tokodon
Name[nl]=tokodon
Name[pl]=tokodon
Name[pt]=tokodon
Name[ru]=tokodon
Name[sl]=tokodon
Name[tr]=tokodon
Name[uk]=tokodon
Name[x-test]=xxtokodonxx

Directories=scalable

[scalable]
Size=22
Type=Scalable
